version: '3'
services:
  namenode:
    image: hadoop-ubuntu:1.0
    container_name: namenode
    hostname: namenode
    ports:
      - "10071:50070"
      - "9000:9000"
      - "9870:9870"
    networks:
      - hadoop
    volumes:
      - namenode_data:/usr/local/hadoop/hdfs/namenode
    command: hdfs namenode

  datanode:
    image: hadoop-ubuntu:1.0
    container_name: datanode
    hostname: datanode
    networks:
      - hadoop
    volumes:
      - datanode_data:/usr/local/hadoop/hdfs/datanode
    command: hdfs datanode

  resourcemanager:
    image: hadoop-ubuntu:1.0
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - "8088:8088"
    networks:
      - hadoop
    command: yarn resourcemanager

  nodemanager:
    image: hadoop-ubuntu:1.0
    container_name: nodemanager
    hostname: nodemanager
    networks:
      - hadoop
    command: yarn nodemanager

networks:
  hadoop:
    driver: bridge

volumes:
  namenode_data:
  datanode_data:
